// Code generated by 'yaegi extract github.com/yourname/nscan/pkg/pluginsdk'. DO NOT EDIT.

package nscan

import (
	"context"
	"github.com/yourname/nscan/pkg/pluginsdk"
	"reflect"
)

func init() {
	Symbols["github.com/yourname/nscan/pkg/pluginsdk/pluginsdk"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Emit":           reflect.ValueOf(pluginsdk.Emit),
		"Log":            reflect.ValueOf(pluginsdk.Log),
		"ReportProgress": reflect.ValueOf(pluginsdk.ReportProgress),
		"Warn":           reflect.ValueOf(pluginsdk.Warn),

		// type definitions
		"Constructor": reflect.ValueOf((*pluginsdk.Constructor)(nil)),
		"Manifest":    reflect.ValueOf((*pluginsdk.Manifest)(nil)),
		"Progress":    reflect.ValueOf((*pluginsdk.Progress)(nil)),
		"ScanResult":  reflect.ValueOf((*pluginsdk.ScanResult)(nil)),
		"Stage":       reflect.ValueOf((*pluginsdk.Stage)(nil)),
		"StageInput":  reflect.ValueOf((*pluginsdk.StageInput)(nil)),

		// interface wrapper definitions
		"_Stage": reflect.ValueOf((*_github_com_yourname_nscan_pkg_pluginsdk_Stage)(nil)),
	}
}

// _github_com_yourname_nscan_pkg_pluginsdk_Stage is an interface wrapper for Stage type
type _github_com_yourname_nscan_pkg_pluginsdk_Stage struct {
	IValue       interface{}
	WGetManifest func() pluginsdk.Manifest
	WRun         func(ctx context.Context, input *pluginsdk.StageInput, params map[string]string, results chan<- *pluginsdk.ScanResult, progress chan<- *pluginsdk.Progress) (*pluginsdk.StageInput, error)
}

func (W _github_com_yourname_nscan_pkg_pluginsdk_Stage) GetManifest() pluginsdk.Manifest {
	return W.WGetManifest()
}
func (W _github_com_yourname_nscan_pkg_pluginsdk_Stage) Run(ctx context.Context, input *pluginsdk.StageInput, params map[string]string, results chan<- *pluginsdk.ScanResult, progress chan<- *pluginsdk.Progress) (*pluginsdk.StageInput, error) {
	return W.WRun(ctx, input, params, results, progress)
}
