// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: scan.proto

package scanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── 节点 → 服务端 ─────────────────────────────────────────────────────────────
type ScannerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ScannerMessage_Register
	//	*ScannerMessage_Heartbeat
	//	*ScannerMessage_Result
	//	*ScannerMessage_Progress
	//	*ScannerMessage_Status
	//	*ScannerMessage_InstallResult
	//	*ScannerMessage_SubtaskProgress
	//	*ScannerMessage_SubtaskComplete
	//	*ScannerMessage_AiPentestResult
	Payload       isScannerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerMessage) Reset() {
	*x = ScannerMessage{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerMessage) ProtoMessage() {}

func (x *ScannerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerMessage.ProtoReflect.Descriptor instead.
func (*ScannerMessage) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScannerMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ScannerMessage) GetPayload() isScannerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScannerMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ScannerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ScannerMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ScannerMessage) GetProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ScannerMessage) GetStatus() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ScannerMessage) GetInstallResult() *InstallResult {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_InstallResult); ok {
			return x.InstallResult
		}
	}
	return nil
}

func (x *ScannerMessage) GetSubtaskProgress() *SubtaskProgress {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_SubtaskProgress); ok {
			return x.SubtaskProgress
		}
	}
	return nil
}

func (x *ScannerMessage) GetSubtaskComplete() *SubtaskComplete {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_SubtaskComplete); ok {
			return x.SubtaskComplete
		}
	}
	return nil
}

func (x *ScannerMessage) GetAiPentestResult() *AIPentestResult {
	if x != nil {
		if x, ok := x.Payload.(*ScannerMessage_AiPentestResult); ok {
			return x.AiPentestResult
		}
	}
	return nil
}

type isScannerMessage_Payload interface {
	isScannerMessage_Payload()
}

type ScannerMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type ScannerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type ScannerMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ScannerMessage_Progress struct {
	Progress *TaskProgress `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type ScannerMessage_Status struct {
	Status *TaskStatusUpdate `protobuf:"bytes,6,opt,name=status,proto3,oneof"`
}

type ScannerMessage_InstallResult struct {
	InstallResult *InstallResult `protobuf:"bytes,7,opt,name=install_result,json=installResult,proto3,oneof"`
}

type ScannerMessage_SubtaskProgress struct {
	SubtaskProgress *SubtaskProgress `protobuf:"bytes,8,opt,name=subtask_progress,json=subtaskProgress,proto3,oneof"`
}

type ScannerMessage_SubtaskComplete struct {
	SubtaskComplete *SubtaskComplete `protobuf:"bytes,9,opt,name=subtask_complete,json=subtaskComplete,proto3,oneof"`
}

type ScannerMessage_AiPentestResult struct {
	AiPentestResult *AIPentestResult `protobuf:"bytes,10,opt,name=ai_pentest_result,json=aiPentestResult,proto3,oneof"`
}

func (*ScannerMessage_Register) isScannerMessage_Payload() {}

func (*ScannerMessage_Heartbeat) isScannerMessage_Payload() {}

func (*ScannerMessage_Result) isScannerMessage_Payload() {}

func (*ScannerMessage_Progress) isScannerMessage_Payload() {}

func (*ScannerMessage_Status) isScannerMessage_Payload() {}

func (*ScannerMessage_InstallResult) isScannerMessage_Payload() {}

func (*ScannerMessage_SubtaskProgress) isScannerMessage_Payload() {}

func (*ScannerMessage_SubtaskComplete) isScannerMessage_Payload() {}

func (*ScannerMessage_AiPentestResult) isScannerMessage_Payload() {}

// ─── 服务端 → 节点 ─────────────────────────────────────────────────────────────
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_Task
	//	*ServerMessage_Cancel
	//	*ServerMessage_Kick
	//	*ServerMessage_Restart
	//	*ServerMessage_InstallTool
	//	*ServerMessage_Subtask
	//	*ServerMessage_AiPentest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetTask() *ScanTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerMessage) GetKick() *KickNode {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

func (x *ServerMessage) GetRestart() *RestartNode {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ServerMessage) GetInstallTool() *InstallTool {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_InstallTool); ok {
			return x.InstallTool
		}
	}
	return nil
}

func (x *ServerMessage) GetSubtask() *AssignSubtask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Subtask); ok {
			return x.Subtask
		}
	}
	return nil
}

func (x *ServerMessage) GetAiPentest() *AIPentestTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AiPentest); ok {
			return x.AiPentest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ack struct {
	Ack *RegisterAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ServerMessage_Task struct {
	Task *ScanTask `protobuf:"bytes,3,opt,name=task,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *CancelTask `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type ServerMessage_Kick struct {
	Kick *KickNode `protobuf:"bytes,5,opt,name=kick,proto3,oneof"`
}

type ServerMessage_Restart struct {
	Restart *RestartNode `protobuf:"bytes,6,opt,name=restart,proto3,oneof"`
}

type ServerMessage_InstallTool struct {
	InstallTool *InstallTool `protobuf:"bytes,7,opt,name=install_tool,json=installTool,proto3,oneof"`
}

type ServerMessage_Subtask struct {
	Subtask *AssignSubtask `protobuf:"bytes,8,opt,name=subtask,proto3,oneof"`
}

type ServerMessage_AiPentest struct {
	AiPentest *AIPentestTask `protobuf:"bytes,9,opt,name=ai_pentest,json=aiPentest,proto3,oneof"`
}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

func (*ServerMessage_Task) isServerMessage_Payload() {}

func (*ServerMessage_Cancel) isServerMessage_Payload() {}

func (*ServerMessage_Kick) isServerMessage_Payload() {}

func (*ServerMessage_Restart) isServerMessage_Payload() {}

func (*ServerMessage_InstallTool) isServerMessage_Payload() {}

func (*ServerMessage_Subtask) isServerMessage_Payload() {}

func (*ServerMessage_AiPentest) isServerMessage_Payload() {}

type KickNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "deleted" | "token_changed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNode) Reset() {
	*x = KickNode{}
	mi := &file_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNode) ProtoMessage() {}

func (x *KickNode) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNode.ProtoReflect.Descriptor instead.
func (*KickNode) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

func (x *KickNode) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RestartNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartNode) Reset() {
	*x = RestartNode{}
	mi := &file_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartNode) ProtoMessage() {}

func (x *RestartNode) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartNode.ProtoReflect.Descriptor instead.
func (*RestartNode) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{3}
}

// ─── 注册 ─────────────────────────────────────────────────────────────────────
type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // 节点名称（自定义）
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                         // 认证 token
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                     // 节点版本
	Capabilities   []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                           // 支持的扫描类型，如 ["port","subdomain","httpx","nuclei"]
	MaxTasks       int32                  `protobuf:"varint,5,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`                  // 最大并发任务数
	InstalledTools []string               `protobuf:"bytes,6,rep,name=installed_tools,json=installedTools,proto3" json:"installed_tools,omitempty"` // 已安装的外部工具，如 ["subfinder","naabu","httpx","nuclei"]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

func (x *RegisterRequest) GetInstalledTools() []string {
	if x != nil {
		return x.InstalledTools
	}
	return nil
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 服务端分配的节点 ID
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─── 心跳 ─────────────────────────────────────────────────────────────────────
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPercent    int32                  `protobuf:"varint,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    int32                  `protobuf:"varint,3,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_scan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemPercent() int32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Heartbeat) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

// ─── 任务下发 ─────────────────────────────────────────────────────────────────
type ScanTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Targets       []string               `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"` // 扫描目标：域名/IP/CIDR
	Config        *TaskConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Blacklist     []*BlacklistRule       `protobuf:"bytes,5,rep,name=blacklist,proto3" json:"blacklist,omitempty"` // 黑名单，用于在节点跳过扫描
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanTask) Reset() {
	*x = ScanTask{}
	mi := &file_scan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTask) ProtoMessage() {}

func (x *ScanTask) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanTask.ProtoReflect.Descriptor instead.
func (*ScanTask) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{7}
}

func (x *ScanTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScanTask) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ScanTask) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ScanTask) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ScanTask) GetBlacklist() []*BlacklistRule {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

type BlacklistRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistRule) Reset() {
	*x = BlacklistRule{}
	mi := &file_scan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRule) ProtoMessage() {}

func (x *BlacklistRule) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRule.ProtoReflect.Descriptor instead.
func (*BlacklistRule) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{8}
}

func (x *BlacklistRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlacklistRule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TaskConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []string               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`                                                                           // 启用的阶段，如 ["subdomain","port","httpx","nuclei"]
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 阶段参数，如 {"port.rate": "1000"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	mi := &file_scan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{9}
}

func (x *TaskConfig) GetStages() []string {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *TaskConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_scan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTask) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ─── 结果上报 ─────────────────────────────────────────────────────────────────
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ResultType    string                 `protobuf:"bytes,3,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"` // "subdomain" | "port" | "http" | "vuln"
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                               // JSON 编码的具体结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_scan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskResult) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *TaskResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Percent       int32                  `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Log           string                 `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`     // 单行日志，kind="log" 时填充
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"` // "info" | "warn" | "error" | "debug"
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_scan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{12}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TaskProgress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TaskProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskProgress) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *TaskProgress) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *TaskProgress) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running" | "done" | "failed"
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_scan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{13}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ─── 工具安装 ─────────────────────────────────────────────────────────────────
type InstallTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InstallCmd    string                 `protobuf:"bytes,2,opt,name=install_cmd,json=installCmd,proto3" json:"install_cmd,omitempty"`
	Reinstall     bool                   `protobuf:"varint,3,opt,name=reinstall,proto3" json:"reinstall,omitempty"` // true 时先卸载旧版再安装
	Uninstall     bool                   `protobuf:"varint,4,opt,name=uninstall,proto3" json:"uninstall,omitempty"` // true 时仅卸载工具（删除二进制），忽略 install_cmd
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallTool) Reset() {
	*x = InstallTool{}
	mi := &file_scan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallTool) ProtoMessage() {}

func (x *InstallTool) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallTool.ProtoReflect.Descriptor instead.
func (*InstallTool) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{14}
}

func (x *InstallTool) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *InstallTool) GetInstallCmd() string {
	if x != nil {
		return x.InstallCmd
	}
	return ""
}

func (x *InstallTool) GetReinstall() bool {
	if x != nil {
		return x.Reinstall
	}
	return false
}

func (x *InstallTool) GetUninstall() bool {
	if x != nil {
		return x.Uninstall
	}
	return false
}

type InstallResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolName       string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	InstalledTools []string               `protobuf:"bytes,4,rep,name=installed_tools,json=installedTools,proto3" json:"installed_tools,omitempty"` // 安装后重新检测的完整工具列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstallResult) Reset() {
	*x = InstallResult{}
	mi := &file_scan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResult) ProtoMessage() {}

func (x *InstallResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResult.ProtoReflect.Descriptor instead.
func (*InstallResult) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{15}
}

func (x *InstallResult) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *InstallResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *InstallResult) GetInstalledTools() []string {
	if x != nil {
		return x.InstalledTools
	}
	return nil
}

// 服务端 → 节点：在用户明确授权后运行 Claude Code。节点只接受服务端生成的目标范围和提示词。
type AIPentestTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Targets        []string               `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ApiKey         string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // transient, never persisted in the task document
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIPentestTask) Reset() {
	*x = AIPentestTask{}
	mi := &file_scan_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIPentestTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIPentestTask) ProtoMessage() {}

func (x *AIPentestTask) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIPentestTask.ProtoReflect.Descriptor instead.
func (*AIPentestTask) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{16}
}

func (x *AIPentestTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AIPentestTask) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AIPentestTask) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AIPentestTask) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AIPentestTask) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type AIPentestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running | done | failed | cancelled
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Log           string                 `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIPentestResult) Reset() {
	*x = AIPentestResult{}
	mi := &file_scan_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIPentestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIPentestResult) ProtoMessage() {}

func (x *AIPentestResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIPentestResult.ProtoReflect.Descriptor instead.
func (*AIPentestResult) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{17}
}

func (x *AIPentestResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AIPentestResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AIPentestResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AIPentestResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *AIPentestResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *AIPentestResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ─── Subtask（Phase 3 分布式队列）─────────────────────────────────────────────
// 服务端 → 节点：分配一个 subtask（通过 ServerMessage.subtask 字段扩展）
type AssignSubtask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskId     string                 `protobuf:"bytes,1,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Targets       []string               `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Blacklist     []*BlacklistRule       `protobuf:"bytes,6,rep,name=blacklist,proto3" json:"blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSubtask) Reset() {
	*x = AssignSubtask{}
	mi := &file_scan_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSubtask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSubtask) ProtoMessage() {}

func (x *AssignSubtask) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSubtask.ProtoReflect.Descriptor instead.
func (*AssignSubtask) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{18}
}

func (x *AssignSubtask) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *AssignSubtask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignSubtask) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *AssignSubtask) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AssignSubtask) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AssignSubtask) GetBlacklist() []*BlacklistRule {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

// 节点 → 服务端：subtask 阶段性进度
type SubtaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskId     string                 `protobuf:"bytes,1,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Percent       int32                  `protobuf:"varint,4,opt,name=percent,proto3" json:"percent,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Log           string                 `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`
	Level         string                 `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	NodeId        string                 `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtaskProgress) Reset() {
	*x = SubtaskProgress{}
	mi := &file_scan_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtaskProgress) ProtoMessage() {}

func (x *SubtaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtaskProgress.ProtoReflect.Descriptor instead.
func (*SubtaskProgress) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{19}
}

func (x *SubtaskProgress) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *SubtaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubtaskProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SubtaskProgress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *SubtaskProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubtaskProgress) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *SubtaskProgress) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SubtaskProgress) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 节点 → 服务端：subtask 完成（成功或失败）
type SubtaskComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskId     string                 `protobuf:"bytes,1,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Output        []byte                 `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"` // JSON 编码的输出资产列表（成功时填充）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtaskComplete) Reset() {
	*x = SubtaskComplete{}
	mi := &file_scan_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtaskComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtaskComplete) ProtoMessage() {}

func (x *SubtaskComplete) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtaskComplete.ProtoReflect.Descriptor instead.
func (*SubtaskComplete) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{20}
}

func (x *SubtaskComplete) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *SubtaskComplete) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubtaskComplete) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SubtaskComplete) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubtaskComplete) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubtaskComplete) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SubtaskComplete) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\ascan.v1\"\xce\x04\n" +
	"\x0eScannerMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x126\n" +
	"\bregister\x18\x02 \x01(\v2\x18.scan.v1.RegisterRequestH\x00R\bregister\x122\n" +
	"\theartbeat\x18\x03 \x01(\v2\x12.scan.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\x06result\x18\x04 \x01(\v2\x13.scan.v1.TaskResultH\x00R\x06result\x123\n" +
	"\bprogress\x18\x05 \x01(\v2\x15.scan.v1.TaskProgressH\x00R\bprogress\x123\n" +
	"\x06status\x18\x06 \x01(\v2\x19.scan.v1.TaskStatusUpdateH\x00R\x06status\x12?\n" +
	"\x0einstall_result\x18\a \x01(\v2\x16.scan.v1.InstallResultH\x00R\rinstallResult\x12E\n" +
	"\x10subtask_progress\x18\b \x01(\v2\x18.scan.v1.SubtaskProgressH\x00R\x0fsubtaskProgress\x12E\n" +
	"\x10subtask_complete\x18\t \x01(\v2\x18.scan.v1.SubtaskCompleteH\x00R\x0fsubtaskComplete\x12F\n" +
	"\x11ai_pentest_result\x18\n" +
	" \x01(\v2\x18.scan.v1.AIPentestResultH\x00R\x0faiPentestResultB\t\n" +
	"\apayload\"\xb6\x03\n" +
	"\rServerMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12(\n" +
	"\x03ack\x18\x02 \x01(\v2\x14.scan.v1.RegisterAckH\x00R\x03ack\x12'\n" +
	"\x04task\x18\x03 \x01(\v2\x11.scan.v1.ScanTaskH\x00R\x04task\x12-\n" +
	"\x06cancel\x18\x04 \x01(\v2\x13.scan.v1.CancelTaskH\x00R\x06cancel\x12'\n" +
	"\x04kick\x18\x05 \x01(\v2\x11.scan.v1.KickNodeH\x00R\x04kick\x120\n" +
	"\arestart\x18\x06 \x01(\v2\x14.scan.v1.RestartNodeH\x00R\arestart\x129\n" +
	"\finstall_tool\x18\a \x01(\v2\x14.scan.v1.InstallToolH\x00R\vinstallTool\x122\n" +
	"\asubtask\x18\b \x01(\v2\x16.scan.v1.AssignSubtaskH\x00R\asubtask\x127\n" +
	"\n" +
	"ai_pentest\x18\t \x01(\v2\x16.scan.v1.AIPentestTaskH\x00R\taiPentestB\t\n" +
	"\apayload\"\"\n" +
	"\bKickNode\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\r\n" +
	"\vRestartNode\"\xbf\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\tmax_tasks\x18\x05 \x01(\x05R\bmaxTasks\x12'\n" +
	"\x0finstalled_tools\x18\x06 \x03(\tR\x0einstalledTools\"\\\n" +
	"\vRegisterAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x89\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x05R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x03 \x01(\x05R\n" +
	"memPercent\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\x05R\vactiveTasks\"\xbf\x01\n" +
	"\bScanTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\x12+\n" +
	"\x06config\x18\x04 \x01(\v2\x13.scan.v1.TaskConfigR\x06config\x124\n" +
	"\tblacklist\x18\x05 \x03(\v2\x16.scan.v1.BlacklistRuleR\tblacklist\"9\n" +
	"\rBlacklistRule\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x98\x01\n" +
	"\n" +
	"TaskConfig\x12\x16\n" +
	"\x06stages\x18\x01 \x03(\tR\x06stages\x127\n" +
	"\x06params\x18\x02 \x03(\v2\x1f.scan.v1.TaskConfig.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"s\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vresult_type\x18\x03 \x01(\tR\n" +
	"resultType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xb2\x01\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x05R\apercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x10\n" +
	"\x03log\x18\x05 \x01(\tR\x03log\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\"Y\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x87\x01\n" +
	"\vInstallTool\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1f\n" +
	"\vinstall_cmd\x18\x02 \x01(\tR\n" +
	"installCmd\x12\x1c\n" +
	"\treinstall\x18\x03 \x01(\bR\treinstall\x12\x1c\n" +
	"\tuninstall\x18\x04 \x01(\bR\tuninstall\"\x8c\x01\n" +
	"\rInstallResult\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12'\n" +
	"\x0finstalled_tools\x18\x04 \x03(\tR\x0einstalledTools\"\x9c\x01\n" +
	"\rAIPentestTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\"\x9b\x01\n" +
	"\x0fAIPentestResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x10\n" +
	"\x03log\x18\x05 \x01(\tR\x03log\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xa4\x02\n" +
	"\rAssignSubtask\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x01 \x01(\tR\tsubtaskId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x12:\n" +
	"\x06params\x18\x05 \x03(\v2\".scan.v1.AssignSubtask.ParamsEntryR\x06params\x124\n" +
	"\tblacklist\x18\x06 \x03(\v2\x16.scan.v1.BlacklistRuleR\tblacklist\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x0fSubtaskProgress\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x01 \x01(\tR\tsubtaskId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x04 \x01(\x05R\apercent\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x10\n" +
	"\x03log\x18\x06 \x01(\tR\x03log\x12\x14\n" +
	"\x05level\x18\a \x01(\tR\x05level\x12\x17\n" +
	"\anode_id\x18\b \x01(\tR\x06nodeId\"\xc7\x01\n" +
	"\x0fSubtaskComplete\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x01 \x01(\tR\tsubtaskId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\x12\x16\n" +
	"\x06output\x18\a \x01(\fR\x06output2M\n" +
	"\vScanService\x12>\n" +
	"\aConnect\x12\x17.scan.v1.ScannerMessage\x1a\x16.scan.v1.ServerMessage(\x010\x01B,Z*github.com/yourname/nscan/pkg/proto/scanv1b\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_scan_proto_goTypes = []any{
	(*ScannerMessage)(nil),   // 0: scan.v1.ScannerMessage
	(*ServerMessage)(nil),    // 1: scan.v1.ServerMessage
	(*KickNode)(nil),         // 2: scan.v1.KickNode
	(*RestartNode)(nil),      // 3: scan.v1.RestartNode
	(*RegisterRequest)(nil),  // 4: scan.v1.RegisterRequest
	(*RegisterAck)(nil),      // 5: scan.v1.RegisterAck
	(*Heartbeat)(nil),        // 6: scan.v1.Heartbeat
	(*ScanTask)(nil),         // 7: scan.v1.ScanTask
	(*BlacklistRule)(nil),    // 8: scan.v1.BlacklistRule
	(*TaskConfig)(nil),       // 9: scan.v1.TaskConfig
	(*CancelTask)(nil),       // 10: scan.v1.CancelTask
	(*TaskResult)(nil),       // 11: scan.v1.TaskResult
	(*TaskProgress)(nil),     // 12: scan.v1.TaskProgress
	(*TaskStatusUpdate)(nil), // 13: scan.v1.TaskStatusUpdate
	(*InstallTool)(nil),      // 14: scan.v1.InstallTool
	(*InstallResult)(nil),    // 15: scan.v1.InstallResult
	(*AIPentestTask)(nil),    // 16: scan.v1.AIPentestTask
	(*AIPentestResult)(nil),  // 17: scan.v1.AIPentestResult
	(*AssignSubtask)(nil),    // 18: scan.v1.AssignSubtask
	(*SubtaskProgress)(nil),  // 19: scan.v1.SubtaskProgress
	(*SubtaskComplete)(nil),  // 20: scan.v1.SubtaskComplete
	nil,                      // 21: scan.v1.TaskConfig.ParamsEntry
	nil,                      // 22: scan.v1.AssignSubtask.ParamsEntry
}
var file_scan_proto_depIdxs = []int32{
	4,  // 0: scan.v1.ScannerMessage.register:type_name -> scan.v1.RegisterRequest
	6,  // 1: scan.v1.ScannerMessage.heartbeat:type_name -> scan.v1.Heartbeat
	11, // 2: scan.v1.ScannerMessage.result:type_name -> scan.v1.TaskResult
	12, // 3: scan.v1.ScannerMessage.progress:type_name -> scan.v1.TaskProgress
	13, // 4: scan.v1.ScannerMessage.status:type_name -> scan.v1.TaskStatusUpdate
	15, // 5: scan.v1.ScannerMessage.install_result:type_name -> scan.v1.InstallResult
	19, // 6: scan.v1.ScannerMessage.subtask_progress:type_name -> scan.v1.SubtaskProgress
	20, // 7: scan.v1.ScannerMessage.subtask_complete:type_name -> scan.v1.SubtaskComplete
	17, // 8: scan.v1.ScannerMessage.ai_pentest_result:type_name -> scan.v1.AIPentestResult
	5,  // 9: scan.v1.ServerMessage.ack:type_name -> scan.v1.RegisterAck
	7,  // 10: scan.v1.ServerMessage.task:type_name -> scan.v1.ScanTask
	10, // 11: scan.v1.ServerMessage.cancel:type_name -> scan.v1.CancelTask
	2,  // 12: scan.v1.ServerMessage.kick:type_name -> scan.v1.KickNode
	3,  // 13: scan.v1.ServerMessage.restart:type_name -> scan.v1.RestartNode
	14, // 14: scan.v1.ServerMessage.install_tool:type_name -> scan.v1.InstallTool
	18, // 15: scan.v1.ServerMessage.subtask:type_name -> scan.v1.AssignSubtask
	16, // 16: scan.v1.ServerMessage.ai_pentest:type_name -> scan.v1.AIPentestTask
	9,  // 17: scan.v1.ScanTask.config:type_name -> scan.v1.TaskConfig
	8,  // 18: scan.v1.ScanTask.blacklist:type_name -> scan.v1.BlacklistRule
	21, // 19: scan.v1.TaskConfig.params:type_name -> scan.v1.TaskConfig.ParamsEntry
	22, // 20: scan.v1.AssignSubtask.params:type_name -> scan.v1.AssignSubtask.ParamsEntry
	8,  // 21: scan.v1.AssignSubtask.blacklist:type_name -> scan.v1.BlacklistRule
	0,  // 22: scan.v1.ScanService.Connect:input_type -> scan.v1.ScannerMessage
	1,  // 23: scan.v1.ScanService.Connect:output_type -> scan.v1.ServerMessage
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	file_scan_proto_msgTypes[0].OneofWrappers = []any{
		(*ScannerMessage_Register)(nil),
		(*ScannerMessage_Heartbeat)(nil),
		(*ScannerMessage_Result)(nil),
		(*ScannerMessage_Progress)(nil),
		(*ScannerMessage_Status)(nil),
		(*ScannerMessage_InstallResult)(nil),
		(*ScannerMessage_SubtaskProgress)(nil),
		(*ScannerMessage_SubtaskComplete)(nil),
		(*ScannerMessage_AiPentestResult)(nil),
	}
	file_scan_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Task)(nil),
		(*ServerMessage_Cancel)(nil),
		(*ServerMessage_Kick)(nil),
		(*ServerMessage_Restart)(nil),
		(*ServerMessage_InstallTool)(nil),
		(*ServerMessage_Subtask)(nil),
		(*ServerMessage_AiPentest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
